apiVersion: apps/v1
kind: Deployment
metadata:
  name: console
  namespace: @@NAME_NS@@
spec:
  progressDeadlineSeconds: 600      
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      hypercloud: ui
      app: console
  template:
    metadata:
      name: hypercloud-ui
      labels:
        hypercloud: ui
        app: console
    spec:
      containers:      
      - command:
        - /opt/bridge/bin/bridge
        - --public-dir=/opt/bridge/static
        - --listen=https://0.0.0.0:6443
        - --tls-cert-file=/var/https-cert/tls.crt
        - --tls-key-file=/var/https-cert/tls.key
        - --hypercloud-endpoint=http://@@HC4@@
        - --prometheus-endpoint=http://@@PROM@@/api
        - --hdc-mode=@@HDC_FLAG@@
        - --tmaxcloud-portal=@@PORTAL@@
        image: 192.168.6.110:5000/hypercloud-console:@@VER@@
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /var/https-cert
          name: https-cert
          readOnly: true
        name: console
        ports:
        - containerPort: 6443
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"        
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      volumes:
      - name: https-cert
        secret:
          defaultMode: 288
          secretName: console-https-secret
