deploy:
  global:
    serviceAccount: "console"
    domain: "tmaxcloud.org"
    consoleDomain: "console"
    hyperAuth:
      address: "hyperauth.tmaxcloud.org"
      realm: "tmax"

  fullnameOverride: "console"

  console:
    clientID: "hypercloud5"

  image:
    tag: "5.2.7.0"

  oauth2proxy:
    config:
      clientID: "hypercloud5"
      clientSecret: ""
      cookieSecret: ""
    redis:
      enabled: false